addons:
  postgresql: 9.6
before_script:
  - gem update --system
  - gem install bundler
  - rails db:setup
dist: trusty
language: ruby
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
