addons:
  postgresql: 9.6
before_script:
  - gem update --system
  - gem install bundler:2.0.1
  - bundle install
  - rails db:setup
language: ruby
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
