addons:
  postgresql: 9.6
before_install:
  - gem update --system --no-rdoc --no-ri
  - gem install bundler:2.0.1 --no-rdoc --no-ri
before_script:
  - bundle exec rails db:create
language: ruby
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
